### PR TITLE
Add MySQL store support

### PR DESCRIPTION
**Pull request by andrejsc**
You're welcome.

### CODE REVIEW

**Comment by andrejsc** [comment]
Tested manually on my development machine:

```bash
go test -v -run TestMySQL
=== RUN   TestMySQL_SessionGetSet
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /set                      --> _/home/andrejs/source/sessions.sessionGetSet.func1 (4 handlers)
[GIN-debug] GET    /get                      --> _/home/andrejs/source/sessions.sessionGetSet.func2 (4 handlers)
[GIN] 2017/01/20 - 15:12:12 | 200 |    3.226891ms |  |   GET     /set
[GIN] 2017/01/20 - 15:12:12 | 200 |     668.237µs |  |   GET     /get
--- PASS: TestMySQL_SessionGetSet (0.01s)
=== RUN   TestMySQL_SessionDeleteKey
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /set                      --> _/home/andrejs/source/sessions.sessionDeleteKey.func1 (4 handlers)
[GIN-debug] GET    /delete                   --> _/home/andrejs/source/sessions.sessionDeleteKey.func2 (4 handlers)
[GIN-debug] GET    /get                      --> _/home/andrejs/source/sessions.sessionDeleteKey.func3 (4 handlers)
[GIN] 2017/01/20 - 15:12:12 | 200 |    2.398659ms |  |   GET     /set
[GIN] 2017/01/20 - 15:12:12 | 200 |     4.37892ms |  |   GET     /delete
[GIN] 2017/01/20 - 15:12:12 | 200 |     498.745µs |  |   GET     /get
--- PASS: TestMySQL_SessionDeleteKey (0.01s)
=== RUN   TestMySQL_SessionFlashes
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /set                      --> _/home/andrejs/source/sessions.sessionFlashes.func1 (4 handlers)
[GIN-debug] GET    /flash                    --> _/home/andrejs/source/sessions.sessionFlashes.func2 (4 handlers)
[GIN-debug] GET    /check                    --> _/home/andrejs/source/sessions.sessionFlashes.func3 (4 handlers)
[GIN] 2017/01/20 - 15:12:12 | 200 |    2.647948ms |  |   GET     /set
[GIN] 2017/01/20 - 15:12:12 | 200 |    4.186907ms |  |   GET     /flash
[GIN] 2017/01/20 - 15:12:12 | 200 |     874.088µs |  |   GET     /check
--- PASS: TestMySQL_SessionFlashes (0.01s)
=== RUN   TestMySQL_SessionClear
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /set                      --> _/home/andrejs/source/sessions.sessionClear.func1 (4 handlers)
[GIN-debug] GET    /check                    --> _/home/andrejs/source/sessions.sessionClear.func2 (4 handlers)
[GIN] 2017/01/20 - 15:12:12 | 200 |    2.401676ms |  |   GET     /set
[GIN] 2017/01/20 - 15:12:12 | 200 |       551.1µs |  |   GET     /check
--- PASS: TestMySQL_SessionClear (0.01s)
=== RUN   TestMySQL_SessionOptions
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /domain                   --> _/home/andrejs/source/sessions.sessionOptions.func1 (4 handlers)
[GIN-debug] GET    /path                     --> _/home/andrejs/source/sessions.sessionOptions.func2 (4 handlers)
[GIN] 2017/01/20 - 15:12:12 | 200 |    2.418289ms |  |   GET     /domain
[GIN] 2017/01/20 - 15:12:12 | 200 |    2.032275ms |  |   GET     /path
--- PASS: TestMySQL_SessionOptions (0.01s)
PASS
ok      _/home/andrejs/source/sessions 0.064s
```

**Comment by appleboy** [comment]
build fail on my local machine like this url:

https://travis-ci.org/gin-contrib/sessions/jobs/193943534

**Comment by andrejsc** [comment]
After some struggling with build server I think I've found what is the problem. It's the inconsistency for session timing. It looks like currently `srinathgs/mysqlstore` is not mature enough. It looks like my patch that solves problem with session options is only the tip of the iceberg on that project.

I'm abandoning this PR for now, and will come back later if I have more time to implement my own variant of MySQL store.

**Comment by appleboy** [comment]
@andrejsc Thanks for your contributions. Looking forward your PR. 👍

**Pull request closed without merging**
