### PR TITLE
Allow for setting redis key prefix.

### PR DESCRIPTION
**Pull request by SilverCory**
This is nice for Database organisation rather than having it all in the root key.

### CODE REVIEW

**Comment by SilverCory** [comment]
#43 
on second thoughts maybe just expose the `*redistore.RediStore`?

**Comment by SilverCory** [comment]
@appleboy can we undo this please, can we expose the redistore?

**Comment by appleboy** [comment]
@SilverCory Why need to undo this PR?

**Comment by SilverCory** [comment]
@appleboy it makes way more sense to expose the actual `*redistore.RediStore`, also that function I created isn't in the public scope because of `store`

**Pull request merged**
