### PR TITLE
Breaking Updates

### PR DESCRIPTION
**Pull request by tmathews**
Includes updates for SameSite, Postgresql, and changes the interface to support error handling. Also removes old Go versions due to http.SameSite not being introduced until Go 1.11.

Feel free to make PRs to my fork, it seems pretty slow over here.

### CODE REVIEW

**Comment by tmathews** [comment]
@thinkerou I think this is ready. Not sure how this org handles breaking changes.

**Comment by tmathews** [comment]
?

**Comment by tmathews** [comment]
Closing this as using this pkg and these updates are silly. Resorting to using pure gorilla session for it's flexibility.

**Comment by pwli-star** [comment]
> Closing this as using this pkg and these updates are silly. Resorting to using pure gorilla session for it's flexibility.

pity, I'm wondering exactly the same feature, don't understand why they don't add.

**Pull request closed without merging**
