### PR TITLE
feat: Add GoRM session store

### PR DESCRIPTION
**Pull request by TJM**
Adds GoRM session store

### CODE REVIEW

**Comment by TJM** [comment]
The test is now failing because of the ancient version of Go. It works on 1.13 and higher (although the error on the old ones says 1.14 :-/  ... anyhow I am not sure how to make it so this specific module is only tested on 1.14 or higher, since its a sub-part. Any tips?

**Comment by bluescreen10** [comment]
Hi, I'm interested on this feature. How can I help to get this merged in?

**Comment by bluescreen10** [comment]
Hey to skip tests on versions lower than 1.13 you can add a build constraint in the test file for example:

gorm/gorm_test.go
```
// +build go1.13
package gorm
...
```

**Comment by TJM** [comment]
I rebased to get rid of the conflicts. I was not sure how to resolve the ones in go.sum.... that file is a mess ;) Maybe `go mod tidy` ? (shrug)

**Comment by bluescreen10** [comment]
`go mod tidy` would certainly clean things up.

**Comment by bluescreen10** [comment]
What do you think @appleboy ?

**Comment by TJM** [comment]
@bluescreen10  - I have a line like the following in my go.mod to use my branch...

```
replace github.com/gin-contrib/sessions => github.com/TJM/sessions v0.0.4-0.20210325232733-5cce4eb28169
```

**Review by appleboy — APPROVED** [review]

**Comment by idc77** [comment]
It's simply gorm not GoRM

**Comment by TJM** [comment]
> It's simply gorm not GoRM. go orm gorm

I updated the MR title, but it was already merged, so the commit message will live on ;)

**Pull request merged**
