### PR TITLE
Support for multiple sessions

### PR DESCRIPTION
**Pull request by karpawich**
In some use cases, a developer needs to access multiple sessions (see [Auth0 Example Go App)](https://github.com/auth0-samples/auth0-golang-web-app/tree/master/01-Login). Using current sessions middleware, developers can only access a single session via the `sessions.GetDefault` function. To avoid breaking changes, this Pull Request introduces two new functions...
- `sessions.SessionsMany(names []string, store Store)`
- `sessions.GetDefaultMany(c *gin.Context, name string)` 

which match the argument patterns of `sessions.Sessions` and `sessions.GetDefault`.

Behind the scenes, these two functions use a `map[string]Session` instead of a `Session` pointer to store multiple Sessions at `DefaultKey` in the Context map accessed by `context.Get` and `context.Set`.

### TODO (Completed 05/24/19)
~~1. Testing~~
~~2. README example~~

A semantically correct update would rename `sessions.Sessions` to `sessions.Session` and reserve the plural form for registering multiple sessions, but I wanted to avoid any breaking changes.

### CODE REVIEW

**Comment by appleboy** [comment]
Please add some example in Readme and some testing

**Comment by karpawich** [comment]
@appleboy I have added testing + README. I revised the README examples section, as you can see.

All tests check out, except for the `embedmd` command. I'm working on that now.

**Comment by karpawich** [comment]
@appleboy This Pull Request is ready to be merged.

**Comment by appleboy** [comment]
@karpawich Thanks

**Comment by appleboy** [comment]
I also release the first version `v0.0.1` for this package.

**Pull request merged**
