### PR TITLE
Use ugorji/go@v1.1.4 instead of ugorji/go/codec.

### LINKED ISSUE #86: cannot load github.com/ugorji/go/codec: ambiguous import: found .... in multiple modules
I wanted to try the [cookie-based session example from the readme](https://github.com/gin-contrib/sessions#cookie-based) but it fails with the following error:

> cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:

To reproduce:

```bash
$ ls -l
total 0
$ go mod init foo
go: creating new go.mod: module foo
$ # copy cookie-based example code into the clipboard
$ pbpaste > ./main.go
$ go fmt ./main.go && go run ./main.go 
go: finding github.com/gin-contrib/sessions latest
go: finding github.com/gin-contrib/sessions/cookie latest
go: finding github.com/gin-gonic/gin v1.4.0
...
go: extracting github.com/gorilla/securecookie v1.1.1
build command-line-arguments: cannot load github.com/ugorji/go/codec: ambiguous import: found github.com/ugorji/go/codec in multiple modules:
	github.com/ugorji/go v1.1.4 (/Users/x/go/pkg/mod/github.com/ugorji/go@v1.1.4/codec)
	github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2 (/Users/x/go/pkg/mod/github.com/ugorji/go/codec@v0.0.0-20181209151446-772ced7fd4c2)
$ echo $?
1
```

I can't tell if this is an [issue with ugorji/go](https://github.com/ugorji/go/issues/291) or [cmd/go itself](https://github.com/golang/go/issues/29332) but thought I'd post here in case anyone knows of a fix. Will update if I find one.

### PR DESCRIPTION
**Pull request by maerics**
Fixes #86 by updating the ugorji/go dependency.

### CODE REVIEW

**Comment by thinkerou** [comment]
please update the whole go mod and file，thanks！

**Comment by thinkerou** [comment]
when you run ‘go mod tidy’, go.mod and go.sum will automatically update.

**Comment by maerics** [comment]
Right. Is that not what we wanted here?

**Comment by thinkerou** [comment]
@maerics gin upgrade 1.4.0 version now, so you also should update gin.
you can run the follow command to update all depend package.
1. `rm go.mod`
2. `rm go.sum`
3. `go mod tidy`
This will update go.mod and go.sum, you commit them to repo.
Thanks!

**Comment by maerics** [comment]
Thank you!

**Pull request merged**
